steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - "push"
      - "gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}"
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'server'
    args:
      - 'run'
      - 'deploy'
      - 'mina-backend'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
