steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'server'
    args:
      - 'cp'
      - 'gs://mina_server_secrets/AuthKey.p8'
      - 'AuthKey.p8'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/mina-295407/mina-backend-builder'
      - '-f'
      - 'Dockerfile.builder'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - "push"
      - 'gcr.io/mina-295407/mina-backend-builder'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - "push"
      - "asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}"
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'server'
    args:
      - 'run'
      - 'deploy'
      - 'mina-backend'
      - '--image'
      - 'asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
timeout: 1200s
