steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'server'
    args:
      - 'cp'
      - 'gs://rust-cache-mina-server/cache.tar.gz'
      - 'musl-build/cache.tar.gz'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - 'build'
      - '-t'
      - 'musl-builder'
      - '-f'
      - 'musl-build/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - 'run'
      - '-v'
      - '$(pwd)/musl-build:/home/rust/src/musl-build'
      - 'musl-builder'
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'server'
    args:
      - 'cp'
      - 'musl-build/cache.tar.gz'
      - 'gs://rust-cache-mina-server/cache.tar.gz'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args:
      - "push"
      - "asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}"
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'server'
    args:
      - 'run'
      - 'deploy'
      - 'mina-backend'
      - '--image'
      - 'asia.gcr.io/${PROJECT_ID}/mina-backend:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
timeout: 1200s
