[config]
default_to_workspace = false


# Postgresサーバーを起動し、マイグレーションを行う
# すでに起動済みの場合でもエラーにしない
[tasks.start-pg]
script = ['''
docker run --rm -d --name mina-dev-pg -p 12781:5432 postgres || true
''']


# Postgresサーバーを停止する
[tasks.stop-pg]
script = ['''
docker stop mina-dev-pg
''']


# DBに接続する
[tasks.connect-pg]
script = ['''
psql "postgres://postgres:postgres@localhost:12781"
''']


# DBのマイグレーションを実行する
[tasks.migrate]
script = ['''
refinery migrate -e DB_URI files -p mina-infra/migrations
''']
env = { DB_URI = "postgres://postgres:postgres@localhost:12781" }

# ローカルサーバーを起動する
[tasks.dev]
command = "cargo"
args = ["run", "--bin", "mina-app"]

[tasks.dev.env]
DATABASE_URL = "postgres://postgres:postgres@localhost:12781"
RUST_LOG = "debug,hyper=info"
PORT = "8080"
