install:
	wget 'https://github.com/skyway/skyway-ios-sdk/releases/download/v3.0.1/SkyWay_iOS_3.0.1.zip'
	unzip SkyWay_iOS_3.0.1.zip -d SkyWay_tmp
	mv SkyWay_tmp/SkyWay.framework Frameworks
	rm -rf SkyWay_iOS_3.0.1.zip SkyWay_tmp
